name: CICD

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install
        run: npm ci
        
      - name: Test
        run: npm test
          
      - name: Lint
        run: npm run lint
        
      - name: Build
        run: npm run build
      
      - name: Copy index.html
        run: |
          cp index.html dist/index.html
          cp dist/index.html dist/404.html
        
      - name: Copy css
        run: |
          mkdir -p dist/assets/css
          cp assets/css/* dist/assets/css/
          
      - name: Copy js
        run: |
          mkdir -p dist/assets/js
          cp assets/js/* dist/assets/js/
          
      - name: Copy img
        run: |
          mkdir -p dist/assets/img
          cp assets/img/* dist/assets/img/
        
      - name : Deploy 🚀 
        uses : JamesIves/github-pages-deploy-action@v4.2.3 
        with :
          branch : gh-pages
          folder : dist
